from archlinux
run yes | pacman -Sy && \
    yes | pacman -S base-devel && \
    yes | pacman -S python-pip python-pipx && \
    yes | pacman -S tectonic texlive-basic texlive-bibtexextra texlive-bin texlive-binextra texlive-games 	texlive-langportuguese 	texlive-latex 	texlive-latexextra 	texlive-latexrecommended 	texlive-luatex 	texlive-mathscience 	texlive-meta 	texlive-pictures texlive-publishers && \
    yes | pip install https://github.com/joh/when-changed/archive/master.zip --break-system-packages